### ISSUE TITLE
Cannot connect to public IP

### ISSUE THREAD

**Issue by srinjoychakravarty** [tryethernal/ethernal#195]
When creating a workspace, I cannot put in a remote public IP address (EC2) as the RPC Server.

![Screenshot 2022-10-03 at 4 41 53 PM](https://user-images.githubusercontent.com/1481037/193678632-93e6b9e1-955b-452f-8d20-49638994d020.png)

**Comment by antoinedc** [comment]
Hi, can you try with adding https:// in front?

**Comment by srinjoychakravarty** [comment]
@antoinedc 

- public ip addresses do not work
- however once I bought and installed a DNS name for that IP address it seems to work over **http**

**Comment by antoinedc** [comment]
I tested your IP and it didn't work with https because there is an issue with the certificate. You can check by running this:
```bash
curl -k --location --request POST https://44.238.178.98:8545 -H "Content-Type: application/json" --data '{"method":"eth_chainId","params":[],"id":1,"jsonrpc":"2.0"}'
```
Now, for http, it actually works but you need to change a setting in your browser. Unfortunately for Ethernal (but I guess there is a good reason for that) browsers do not allow loading insecure (http or ws) content on a https page. In order to change that you can follow instructions here: https://experienceleague.adobe.com/docs/target/using/experiences/vec/troubleshoot-composer/mixed-content.html

Once this is done, you should be able to connect your ip over http.
